// WARNING: This file is regenerated by the `cargo func new` command.

mod add;
mod entities;
mod random;
mod redirect;
mod slack;
mod slack_command_handler;
mod slack_command_receiver;
mod table;

// Export the Azure Functions here.
azure_functions::export! {
    add::add,
    random::random,
    redirect::redirect,
    slack::slack,
    slack_command_handler::slack_command_handler,
    slack_command_receiver::slack_command_receiver,
}
