// WARNING: This file is regenerated by the `cargo func new` command.

mod add;
mod random;
mod redirect;

// Export the Azure Functions here.
azure_functions::export! {
    add::add,
    random::random,
    redirect::redirect,
}
